class DeadMenu {
    constructor() {
        this['gameEnded'] = ![], this['gameEndedFadeTimer'] = 0x0, this['acceptedDeath'] = ![], this['hoveringOverButton'] = ![], this['hoveringOverRematchButton'] = ![], this['rematchRequested'] = ![];
    }
    ['drawDeadFlower'](_0x305c50, _0x558593, _0x4fe0ff) {
        ctx['fillStyle'] = '#ffe763', ctx['strokeStyle'] = '#cebb50', ctx['lineWidth'] = _0x4fe0ff / 0x8, ctx['beginPath'](), ctx['arc'](_0x305c50, _0x558593, _0x4fe0ff, 0x0, Math['PI'] * 0x2), ctx['fill'](), ctx['stroke'](), ctx['closePath'](), ctx['fillStyle'] = '#212219', ctx['strokeStyle'] = ctx['fillStyle'], ctx['lineWidth'] = _0x4fe0ff / 0x8, ctx['lineCap'] = 'round';
        let _0x27be1 = {
            'x': _0x305c50 - _0x4fe0ff / 3.5,
            'y': _0x558593 - _0x4fe0ff * 0x5 / 23.5
        };
        ctx['beginPath'](), ctx['moveTo'](_0x27be1['x'] + _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] + _0x4fe0ff * 0x4 / 23.5), ctx['lineTo'](_0x27be1['x'] - _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] - _0x4fe0ff * 0x4 / 23.5), ctx['stroke'](), ctx['closePath'](), ctx['beginPath'](), ctx['moveTo'](_0x27be1['x'] + _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] - _0x4fe0ff * 0x4 / 23.5), ctx['lineTo'](_0x27be1['x'] - _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] + _0x4fe0ff * 0x4 / 23.5), ctx['stroke'](), ctx['closePath'](), _0x27be1 = {
            'x': _0x305c50 + _0x4fe0ff / 3.5,
            'y': _0x558593 - _0x4fe0ff * 0x5 / 23.5
        }, ctx['beginPath'](), ctx['moveTo'](_0x27be1['x'] + _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] + _0x4fe0ff * 0x4 / 23.5), ctx['lineTo'](_0x27be1['x'] - _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] - _0x4fe0ff * 0x4 / 23.5), ctx['stroke'](), ctx['closePath'](), ctx['beginPath'](), ctx['moveTo'](_0x27be1['x'] + _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] - _0x4fe0ff * 0x4 / 23.5), ctx['lineTo'](_0x27be1['x'] - _0x4fe0ff * 0x4 / 23.5, _0x27be1['y'] + _0x4fe0ff * 0x4 / 23.5), ctx['stroke'](), ctx['closePath'](), ctx['strokeStyle'] = ctx['fillStyle'], ctx['lineWidth'] = _0x4fe0ff / 0xf, ctx['lineCap'] = 'round';
        let _0x4dedd7 = 0x1;
        ctx['beginPath'](), ctx['moveTo'](_0x305c50 + _0x4fe0ff / 0x4, _0x558593 + _0x4fe0ff * 9.5 / 23.5), ctx['quadraticCurveTo'](_0x305c50, _0x558593 + 1.07 * _0x4fe0ff * (5.5 + 9.5 * (0x1 - _0x4dedd7)) / 23.5 * 61.1 / 0x46, _0x305c50 - _0x4fe0ff / 0x4, _0x558593 + _0x4fe0ff * 9.5 / 23.5), ctx['stroke']();
    }
    ['draw']() {
        ctx['globalAlpha'] = 0.2, ctx['fillStyle'] = 'black', ctx['fillRect'](0x0, 0x0, canvas['w'], canvas['h']), ctx['globalAlpha'] = 0x1, this['gameEnded'] === !![] ? ctx['globalAlpha'] = 0x1 - Math['min'](0x1, this['gameEndedFadeTimer'] / 0x1e) : ctx['globalAlpha'] = 0x1, ctx['translate'](0x0, -0x1a), this['acceptedDeath'] == !![] ? this['drawWaiting']() : this['drawDead'](), this['gameEnded'] === !![] && (this['gameEndedFadeTimer']++, ctx['globalAlpha'] = Math['min'](0x1, this['gameEndedFadeTimer'] / 0x1e), this['drawGameOver']()), ctx['translate'](0x0, 0x1a), collectedMenu['draw'](), ctx['textBaseline'] = 'middle';
    }
    ['drawDead']() {
        ctx['save'](), ctx['translate'](canvas['w'] / 0x2, canvas['h'] / 0x2), this['drawDeadPetal'](-0xf, -0x14, inventory['topPetalContainers'][0x3]), this['drawDeadPetal'](0x28, -0xa, inventory['topPetalContainers'][0x4]), this['drawDeadPetal'](-0x32, 0xa, inventory['topPetalContainers'][0x2]), ctx['restore']();
        const _0x5dab28 = -0.2;
        ctx['save'](), ctx['translate'](canvas['w'] / 0x2, canvas['h'] / 0x2), ctx['rotate'](_0x5dab28), this['drawDeadFlower'](0x0, 0x0, 0x23), ctx['restore'](), ctx['save'](), ctx['translate'](canvas['w'] / 0x2, canvas['h'] / 0x2), this['drawDeadPetal'](-0xf, 0x2d, inventory['topPetalContainers'][0x1]), this['drawDeadPetal'](0x32, 0x1e, inventory['topPetalContainers'][0x0]), ctx['restore']();
        let _0x179368 = window['lastHitBy'] || 'A\x20Skill\x20Issue';
        ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2016px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('You\x20were\x20destroyed\x20by:', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x78), ctx['fillText']('You\x20were\x20destroyed\x20by:', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x78), ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['strokeText'](_0x179368, canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x55), ctx['fillText'](_0x179368, canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x55), ctx['restore'](), this['buttonDimensions'] = {
            'x': canvas['w'] / 0x2 - 34.2266 * 0x4 / 0x2,
            'y': canvas['h'] / 0x2 + 19.5 * 0x4,
            'w': 34.2266 * 0x4,
            'h': 0x28
        };
        const _0x577e1d = mouse['canvasX'], _0x2e7292 = mouse['canvasY'];
        if (this['gameEnded'] === ![] && this['acceptedDeath'] == ![] && _0x577e1d > this['buttonDimensions']['x'] && _0x577e1d < this['buttonDimensions']['x'] + this['buttonDimensions']['w'] && _0x2e7292 > this['buttonDimensions']['y'] - 0x1a && _0x2e7292 < this['buttonDimensions']['y'] + this['buttonDimensions']['h'] - 0x1a)
            this['hoveringOverButton'] = !![], this['hoveringOverRematchButton'] = ![], setCursor('pointer');
        else
            this['gameEnded'] === ![] && (!window['inMainPvpRoom'] || window['deadMenuTime'] >= 0x1388) && this['acceptedDeath'] == ![] && _0x577e1d > this['buttonDimensions']['x'] && _0x577e1d < this['buttonDimensions']['x'] + this['buttonDimensions']['w'] && _0x2e7292 > this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 - 0x1a && _0x2e7292 < this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] - 0x1a ? (this['hoveringOverRematchButton'] = !![], this['hoveringOverButton'] = ![], setCursor('pointer')) : (this['hoveringOverButton'] = ![], this['hoveringOverRematchButton'] = ![]);
        ctx['globalAlpha'] = 0x1, ctx['fillStyle'] = this['hoveringOverButton'] ? '#1cd128' : '#10c21a', ctx['lineWidth'] = 0x6, ctx['strokeStyle'] = blendColor(ctx['fillStyle'], '#000000', 0.2), ctx['beginPath'](), ctx['roundRect'](this['buttonDimensions']['x'], this['buttonDimensions']['y'], this['buttonDimensions']['w'], this['buttonDimensions']['h'], 0x6), ctx['fill'](), ctx['stroke'](), ctx['closePath'](), ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('Continue', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Continue', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] / 0x2);
        if (biomeManager !== undefined && biomeManager['getCurrentBiome']() === '1v1') {
            let _0x391929 = ![];
            window['inMainPvpRoom'] && (window['deadMenuTime'] < 0x1388 && (_0x391929 = !![])), !_0x391929 ? (ctx['globalAlpha'] = 0x1, ctx['fillStyle'] = this['hoveringOverRematchButton'] ? '#1cd128' : '#10c21a', ctx['lineWidth'] = 0x6, ctx['strokeStyle'] = blendColor(ctx['fillStyle'], '#000000', 0.2), ctx['beginPath'](), ctx['roundRect'](this['buttonDimensions']['x'], this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28, this['buttonDimensions']['w'], this['buttonDimensions']['h'], 0x6), ctx['fill'](), ctx['stroke'](), ctx['closePath'](), ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('Rematch', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Rematch', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['restore'](), this['rematchRequested'] === !![] && (ctx['lineWidth'] = 0x2, ctx['fillStyle'] = 'white', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2020px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'left', ctx['strokeText']('Rematch\x20requested...', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] + 0xa, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Rematch\x20requested...', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] + 0xa, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2))) : (ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('You\x20may\x20rematch\x20in:\x20' + Math['floor']((0x1388 - window['deadMenuTime']) / 0x64) / 0xa + 's', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('You\x20may\x20rematch\x20in:\x20' + Math['floor']((0x1388 - window['deadMenuTime']) / 0x64) / 0xa + 's', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['restore']());
        }
        ctx['restore']();
    }
    ['drawWaiting']() {
        this['buttonDimensions'] = {
            'x': canvas['w'] / 0x2 - 34.2266 * 0x6 / 0x2,
            'y': canvas['h'] / 0x2 + 19.5 * 0x4 / 0x2,
            'w': 34.2266 * 0x6,
            'h': 0x28
        };
        const _0x84ddd8 = mouse['canvasX'], _0x50349a = mouse['canvasY'];
        this['gameEnded'] === ![] && this['acceptedDeath'] == !![] && _0x84ddd8 > this['buttonDimensions']['x'] && _0x84ddd8 < this['buttonDimensions']['x'] + this['buttonDimensions']['w'] && _0x50349a > this['buttonDimensions']['y'] - 0x1a && _0x50349a < this['buttonDimensions']['y'] + this['buttonDimensions']['h'] - 0x1a ? (this['hoveringOverButton'] = !![], setCursor('pointer')) : (this['hoveringOverButton'] = ![], this['hoveringOverRematchButton'] = ![]), ctx['fillStyle'] = this['hoveringOverButton'] ? '#d94747' : '#d11d1d', ctx['lineWidth'] = 0x6, ctx['strokeStyle'] = blendColor(ctx['fillStyle'], '#000000', 0.2), ctx['beginPath'](), ctx['roundRect'](this['buttonDimensions']['x'], this['buttonDimensions']['y'], this['buttonDimensions']['w'], this['buttonDimensions']['h'], 0x6), ctx['fill'](), ctx['stroke'](), ctx['closePath'](), ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2018px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('Leave\x20Game\x20Instead', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Leave\x20Game\x20Instead', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] / 0x2), ctx['restore'](), ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2018px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('You\x20will\x20respawn\x20next\x20wave', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x5), ctx['fillText']('You\x20will\x20respawn\x20next\x20wave', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x5), ctx['restore']();
    }
    ['drawGameOver']() {
        this['buttonDimensions'] = {
            'x': canvas['w'] / 0x2 - 34.2266 * 0x4 / 0x2,
            'y': canvas['h'] / 0x2 + 19.5 * 0x4 / 0x2,
            'w': 34.2266 * 0x4,
            'h': 0x28
        };
        const _0x4f08b9 = mouse['canvasX'], _0x5256d8 = mouse['canvasY'];
        if (this['gameEnded'] === !![] && this['acceptedDeath'] == !![] && _0x4f08b9 > this['buttonDimensions']['x'] && _0x4f08b9 < this['buttonDimensions']['x'] + this['buttonDimensions']['w'] && _0x5256d8 > this['buttonDimensions']['y'] - 0x1a && _0x5256d8 < this['buttonDimensions']['y'] + this['buttonDimensions']['h'] - 0x1a)
            this['hoveringOverButton'] = !![], this['hoveringOverRematchButton'] = ![], setCursor('pointer');
        else
            this['gameEnded'] === !![] && (!window['inMainPvpRoom'] || window['deadMenuTime'] >= 0x1388) && this['acceptedDeath'] == !![] && _0x4f08b9 > this['buttonDimensions']['x'] && _0x4f08b9 < this['buttonDimensions']['x'] + this['buttonDimensions']['w'] && _0x5256d8 > this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 - 0x1a && _0x5256d8 < this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] - 0x1a ? (this['hoveringOverRematchButton'] = !![], this['hoveringOverButton'] = ![], setCursor('pointer')) : (this['hoveringOverButton'] = ![], this['hoveringOverRematchButton'] = ![]);
        ctx['fillStyle'] = this['hoveringOverButton'] ? '#d94747' : '#d11d1d', ctx['lineWidth'] = 0x6, ctx['strokeStyle'] = blendColor(ctx['fillStyle'], '#000000', 0.2), ctx['beginPath'](), ctx['roundRect'](this['buttonDimensions']['x'], this['buttonDimensions']['y'], this['buttonDimensions']['w'], this['buttonDimensions']['h'], 0x6), ctx['fill'](), ctx['stroke'](), ctx['closePath'](), ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('Continue', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Continue', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] / 0x2), ctx['restore']();
        if (biomeManager !== undefined && biomeManager['getCurrentBiome']() === '1v1') {
            let _0x1aa04d = ![];
            window['inMainPvpRoom'] && (window['deadMenuTime'] < 0x1388 && (_0x1aa04d = !![])), !_0x1aa04d ? (ctx['globalAlpha'] = 0x1, ctx['fillStyle'] = this['hoveringOverRematchButton'] ? '#1cd128' : '#10c21a', ctx['lineWidth'] = 0x6, ctx['strokeStyle'] = blendColor(ctx['fillStyle'], '#000000', 0.2), ctx['beginPath'](), ctx['roundRect'](this['buttonDimensions']['x'], this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28, this['buttonDimensions']['w'], this['buttonDimensions']['h'], 0x6), ctx['fill'](), ctx['stroke'](), ctx['closePath'](), ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('Rematch', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Rematch', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['restore'](), this['rematchRequested'] === !![] && (ctx['lineWidth'] = 0x2, ctx['fillStyle'] = 'white', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2020px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'left', ctx['strokeText']('Rematch\x20requested...', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] + 0xa, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('Rematch\x20requested...', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] + 0xa, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2))) : (ctx['save'](), ctx['letterSpacing'] = '0.5px', ctx['fillStyle'] = '#f0f0f0', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2022px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x3, ctx['strokeText']('You\x20may\x20rematch\x20in:\x20' + Math['floor']((0x1388 - window['deadMenuTime']) / 0x64) + 's', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['fillText']('You\x20may\x20rematch\x20in:\x20' + Math['floor']((0x1388 - window['deadMenuTime']) / 0x64) + 's', this['buttonDimensions']['x'] + this['buttonDimensions']['w'] / 0x2, this['buttonDimensions']['y'] + this['buttonDimensions']['h'] * 1.28 + this['buttonDimensions']['h'] / 0x2), ctx['restore']());
        }
        ctx['save'](), ctx['letterSpacing'] = '1px', ctx['fillStyle'] = '#8a0000', ctx['strokeStyle'] = 'black', ctx['font'] = '900\x2056px\x20\x27Ubuntu\x27', ctx['textAlign'] = 'center', ctx['textBaseline'] = 'middle', ctx['lineWidth'] = 0x6, window['hasWonPvp'] === !![] ? (ctx['fillStyle'] = '#008a2e', ctx['strokeText']('You\x20win!', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x5), ctx['fillText']('You\x20win!', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x5)) : (ctx['strokeText']('Game\x20Over', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x5), ctx['fillText']('Game\x20Over', canvas['w'] / 0x2, canvas['h'] / 0x2 - 0x5)), ctx['restore']();
    }
    ['drawDeadPetal'](_0x47905a, _0x5d6b22, _0x4c1864) {
        if (!_0x4c1864 || !_0x4c1864['petals'] || !_0x4c1864['petals'][0x0])
            return;
        let _0xb5ec2b = new Petal(_0x4c1864['petals'][0x0]);
        ctx['translate'](_0x47905a, _0x5d6b22), ctx['scale'](0x2, 0x2), _0xb5ec2b['draw'](), ctx['scale'](0x1 / 0x2, 0x1 / 0x2), ctx['translate'](-_0x47905a, -_0x5d6b22);
    }
    ['gameOver']() {
        this['gameEndedFadeTimer'] = 0x0, this['gameEnded'] = !![], this['acceptedDeath'] = !![];
    }
    ['unGameOver']() {
        this['gameEndedFadeTimer'] = 0x0, this['gameEnded'] = ![], this['acceptedDeath'] = ![];
    }
}